In [1]:
# Import libraries
import requests
import os
import pandas as pd
from helpers import *
from inspect_helpers import *

In [2]:
# Use example given on website
query = "WHOSIS_000001?$filter=Dim1 eq 'MLE' and date(TimeDimensionBegin) ge 2011-01-01 and date(TimeDimensionBegin) lt 2012-01-01" # "Life expectancy at birth"

initial_query = query_who(query)

Response: 200

In [3]:
list_dimensions()

Response: 200

                   Code                                    Title
0       ADVERTISINGTYPE        SUBSTANCE_ABUSE_ADVERTISING_TYPES
1              AGEGROUP                                Age Group
2           ALCOHOLTYPE                           Beverage Types
3      AMRGLASSCATEGORY                       AMR GLASS Category
4            ANTIBIOTIC                               Antibiotic
..                  ...                                      ...
184      WPR_DATASOURCE                         WPRO Data Source
185        WPR_DEMO_IND                      WPRO Demo Indicator
186  WRS_OUTSIDE_REPORT  WRs from outside the region year report
187          WRS_STATUS                WHO Representative Status
188                YEAR                                     Year

[189 rows x 2 columns]

In [4]:
list_indicators()

Response: 200

,IndicatorCode,IndicatorName,Language
0,AIR_18,Household air pollution attributable DALYs pe...,EN
1,AIR_4,Ambient air pollution attributable deaths in c...,EN
2,AIR_11,Household air pollution attributable deaths,EN
3,AIR_13,Household air pollution attributable deaths pe...,EN
4,AIR_14,Household air pollution attributable deaths p...,EN
...,...,...,...
2998,P_compl_p3,Compliance with smoke-free universities law (s...,EN
2999,E21a_direct_ad_fines,Law requires fines for violations of advertisi...,EN
3000,NCD_CCS_urine_strips_gluc_ketone,General availability of urine strips for gluco...,EN
3001,E21b_indirect_ad_fines,Law requires fines for violations of promotion...,EN
3002,HEPATITIS_HBV_TREATMENT_PERDIAGNOSED_PER100,Chronic hepatitis B (HBV) treatment rate as pe...,EN

### Retrieving a list of available values for a specific dimension
By appending a dimension code and the DimensionValues parameter to the OData URL you can retrieve the list of values associated with that specific dimension. For example, to retrieve the list of the COUNTRY dimension values, use the following link:

In [35]:
query = "DIMENSION/COUNTRY/DimensionValues"

query_who(query=query)

Response: 200

,Code,Title,ParentDimension,Dimension,ParentCode,ParentTitle
0,ABW,Aruba,REGION,COUNTRY,AMR,Americas
1,AFG,Afghanistan,REGION,COUNTRY,EMR,Eastern Mediterranean
2,AGO,Angola,REGION,COUNTRY,AFR,Africa
3,AIA,Anguilla,REGION,COUNTRY,AMR,Americas
4,ALB,Albania,REGION,COUNTRY,EUR,Europe
...,...,...,...,...,...,...
229,XKX,Kosovo (in accordance with UN Security Council...,None,COUNTRY,None,None
230,YEM,Yemen,REGION,COUNTRY,EMR,Eastern Mediterranean
231,ZAF,South Africa,REGION,COUNTRY,AFR,Africa
232,ZMB,Zambia,REGION,COUNTRY,AFR,Africa
233,ZWE,Zimbabwe,REGION,COUNTRY,AFR,Africa

## Retrieving the indicators list

Simply specifying the /api/Indicator URL will provide you with the list of indicators:

https://ghoapi.azureedge.net/api/Indicator

To select only the indicators which contain a specific text, query the data using the following example. In this example, all indicators containing 'Household' were queried:

https://ghoapi.azureedge.net/api/Indicator?$filter=contains(IndicatorName,'Household')

To select only the indicators that have a specific title, query the data using the following example. In this example, the indicator 'Ambient air pollution attributable deaths' was queried:

https://ghoapi.azureedge.net/api/Indicator?$filter=IndicatorName eq 'Ambient air pollution attributable deaths'

In [37]:
query = "Indicator"
indicators_df = query_who(query=query)

Response: 200

In [38]:
indicators_df.head()

  IndicatorCode                                      IndicatorName Language
0        AIR_18  Household air pollution  attributable DALYs pe...       EN
1         AIR_4  Ambient air pollution attributable deaths in c...       EN
2        AIR_11        Household air pollution attributable deaths       EN
3        AIR_13  Household air pollution attributable deaths pe...       EN
4        AIR_14  Household air pollution  attributable deaths p...       EN

In [52]:
def list_indicators(indicators_df=indicators_df):
    
    if indicators_df is None:
        indicators_df = query_who("Indicator")

    return indicators_df

In [53]:
list_indicators()

,IndicatorCode,IndicatorName,Language
0,AIR_18,Household air pollution attributable DALYs pe...,EN
1,AIR_4,Ambient air pollution attributable deaths in c...,EN
2,AIR_11,Household air pollution attributable deaths,EN
3,AIR_13,Household air pollution attributable deaths pe...,EN
4,AIR_14,Household air pollution attributable deaths p...,EN
...,...,...,...
2998,P_compl_p3,Compliance with smoke-free universities law (s...,EN
2999,E21a_direct_ad_fines,Law requires fines for violations of advertisi...,EN
3000,NCD_CCS_urine_strips_gluc_ketone,General availability of urine strips for gluco...,EN
3001,E21b_indirect_ad_fines,Law requires fines for violations of promotion...,EN
3002,HEPATITIS_HBV_TREATMENT_PERDIAGNOSED_PER100,Chronic hepatitis B (HBV) treatment rate as pe...,EN

In [47]:
def search_indicators(query, indicators_df=indicators_df):
    
    # If indiactors_df not provided, query_who
    if indicators_df is None:
        print("Querying WHO...")
        indicators_df = query_who("Indicator")

    mask = indicators_df['IndicatorName'].str.contains("air", case=False, na=False)

    filtered_df = indicators_df[mask]

    results_count = len(filtered_df)

    print(f"{results_count} results found.")

    return filtered_df

In [ ]:
search_indicators("smoke")

44 results found.

,IndicatorCode,IndicatorName,Language
0,AIR_18,Household air pollution attributable DALYs pe...,EN
1,AIR_4,Ambient air pollution attributable deaths in c...,EN
2,AIR_11,Household air pollution attributable deaths,EN
3,AIR_13,Household air pollution attributable deaths pe...,EN
4,AIR_14,Household air pollution attributable deaths p...,EN
5,AIR_17,Household air pollution attributable DALYs (pe...,EN
7,AIR_50,Ambient air pollution attributable deaths (per...,EN
8,AIR_51,Household air pollution attributable death rat...,EN
9,AIR_52,Household air pollution attributable death rat...,EN
10,AIR_63,Household and ambient air pollution attributab...,EN
11,AIR_39,Household air pollution attributable DALYs (pe...,EN
12,AIR_41,Ambient air pollution attributable deaths,EN
13,AIR_43,Ambient air pollution attributable DALYs,EN
14,AIR_44,DALYs attributable to ambient air pollution (a...,EN
15,AIR_9,Ambient air pollution attributable DALYs (per...,EN
23,AIR_61,Household and ambient air pollution attributab...,EN
24,AIR_8,Ambient air pollution attributable DALYs in c...,EN
25,AIR_90,Ambient air pollution attributable DALYs (per...,EN
42,Camp_tv_radio,Campaign aired on television and/or radio,EN
81,AIR_10,Ambient air pollution attributable DALYs per ...,EN
82,AIR_12,Household air pollution attributable deaths in...,EN
83,AIR_16,Household air pollution attributable DALYs in ...,EN
85,AIR_35,Joint effects of air pollution attributable de...,EN
86,AIR_36,Joint effects of air pollution attributable de...,EN
92,AIR_42,Ambient air pollution attributable death rate ...,EN
93,AIR_46,YLLs attributable to ambient air pollution (ag...,EN
94,AIR_5,Ambient air pollution attributable death rate ...,EN
100,AIR_6,Ambient air pollution attributable deaths per...,EN
101,AIR_60,Household and ambient air pollution attributab...,EN
102,AIR_62,Household and ambient air pollution attributab...,EN
155,AIR_15,Household air pollution attributable DALYs,EN
156,AIR_45,Ambient air pollution attributable YLLs,EN
161,AIR_7,Ambient air pollution attributable DALYs,EN
788,OCC_5,Occupational airborne particulates attributabl...,EN
804,OCC_8,Occupational airborne particulates attributabl...,EN
946,OCC_6,Occupational airborne particulates attributabl...,EN
947,OCC_7,Occupational airborne particulates attributabl...,EN
1633,SDGAIRBOD,Ambient and household air pollution attributab...,EN
1770,SDGAIRBODA,Ambient and household air pollution attributab...,EN
2377,AIR_73,Ambient air pollution attributable YLL in chil...,EN
2513,AIR_74,Household air pollution attributable deaths in...,EN
2576,AIR_71,Ambient air pollution attributable DALYs in ch...,EN
2925,AIR_72,Ambient air pollution attributable deaths in c...,EN
2964,AIR_75,Household air pollution attributable DALYs in ...,EN